# Generated by Django 5.1.2 on 2024-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('methane', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
