# Generated by Django 5.1.2 on 2024-10-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_sensordata_spoilage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringgroup',
            name='email_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
