# Generated by Django 5.1.2 on 2024-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_monitoringgroup_email_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringgroup',
            name='phone_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
