# Generated by Django 5.1.2 on 2024-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='ammonia',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
