# Generated by Django 5.1.2 on 2024-12-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0011_sensordata_reason_of_spoilage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringgroup',
            name='food_type',
            field=models.CharField(choices=[('menudo', 'Menudo'), ('adobo', 'Adobo'), ('mechado', 'Mechado'), ('general', 'General')], max_length=50),
        ),
    ]
