# Generated by Django 5.1.2 on 2024-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0012_alter_monitoringgroup_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='ammonia',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='methane',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
