# Generated by Django 5.1.2 on 2024-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0013_alter_sensordata_ammonia_alter_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='methane_status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='storage_status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature_status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
