# Generated by Django 5.1.2 on 2024-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0015_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='food_type',
            field=models.CharField(choices=[('menudo', 'Menudo'), ('adobo', 'Adobo'), ('mechado', 'Mechado'), ('bicol', 'Bicol')], max_length=50, null=True),
        ),
    ]
